query FeedSearch($filter: String!) {
  feed(filter: $filter) {
    id
    links {
      id
      url
      description
      createdAt
      postedBy {
        id
        name
      }
      votes {
        id
        user {
          id
        }
      }
    }
  }
}
